"""Add external_id column to jobs table

Revision ID: 386d5a0fe9db
Revises: 142dbd449db8
Create Date: 2025-03-09 15:19:10.692775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386d5a0fe9db'
down_revision: Union[str, None] = '142dbd449db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'job_applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'job_applications', 'jobs', ['job_id'], ['id'])
    op.add_column('jobs', sa.Column('external_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'jobs', ['external_id'])
    op.create_index(op.f('ix_resumes_file_path'), 'resumes', ['file_path'], unique=False)
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_index(op.f('ix_resumes_file_path'), table_name='resumes')
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'external_id')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    # ### end Alembic commands ###
