"""Fix JobMatch import issue

Revision ID: f01f2f694d92
Revises: f9a5ec1cc7c9
Create Date: 2025-03-14 11:12:13.186133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01f2f694d92'
down_revision: Union[str, None] = 'f9a5ec1cc7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
